  version: "3"
  services:
    xxl-job-executor:
      image: pumbaapeng/xxl-job-executor:latest
      ports:
        - "8081:8081"
      networks:
        - xxlnet
      depends_on:
        - xxl-mysql
      command: ["./wait-for-it.sh", "xxl-mysql:3306", "--", "sh", "-c", "java -jar /app.jar"]

    xxl-job-admin:
      image: pumbaapeng/xxl-job-admin:latest
      ports:
        - "4000:8080"
      networks:
        - xxlnet
      depends_on:
        - xxl-mysql
      command: ["./wait-for-it.sh", "xxl-mysql:3306", "--", "sh", "-c", "java -jar /app.jar"]

    xxl-mysql:
      image: pumbaapeng/xxl-mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: root_pwd
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      ports:
        - "3306:3306"
      networks:
        - xxlnet
  networks:
    xxlnet:
