version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql8.0
    volumes:
      - /Users/pumbaa/Developer/docker/data/mysql8.0:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
